name: "Build php-fpm image"

on:
  schedule:
    - cron: 0 0 * * 0

  push:
    branches:
      - main

env:
  PHP_VERSION: "8.3"

jobs:
  build-and-deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/einfach-gaming/php-fpm:${{ env.PHP_VERSION }}
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}
          outputs: type=image,push=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

